import type { Metadata } from "next";
import { Sora, JetBrains_Mono } from "next/font/google";
import "./globals.css";

import Sidebar from "./_components/sidebar";
import { Toaster } from "sonner";

const sora = Sora({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800"],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} ${jetbrainsMono.className} antialiased`}
      >
        <div className="flex gap-4">
          <Sidebar /> {children}
        </div>
        <Toaster
          toastOptions={{
            style: {
              background: "#9333ea",
              color: "#fff",
            },
          }}
        />
      </body>
    </html>
  );
}
